theme = "hyde"
baseURL = "/"
defaultContentLanguage = "UTF-8"
languageCode = "UTF-8"
title = "Alexander Kirchner-Häusler"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[[menu.main]]
    name = "About"
    weight = 1
    url = "/about"
	
[[menu.main]]
    name = "Project"
    weight = 2
    url = "https://honorlogic.org"
	
[params]
  description = "Culture, Emotion, Relationships"
  themeColor = "theme-base-08"
